# Generated by Django 5.0.7 on 2024-08-04 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_learnerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
