# Generated by Django 5.0.7 on 2024-08-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_learnerprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='email',
        ),
    ]
